# Short tutorial on how to open and delete columns in a csv file

In [5]:
# Import the pandas library and 'save' it as 'pd' : 

import pandas as pd

In [6]:
# open the original file and save it as 'dataset':
dataset = pd.read_csv('C:\cern data/DoubleMuRun2011A.csv')
# Display the top of data:
dataset.head()

,Run,Event,Type1,E1,px1,py1,pz1,pt1,eta1,phi1,...,Type2,E2,px2,py2,pz2,pt2,eta2,phi2,Q2,M
0,165617,74601703,G,9.69873,-9.510430,0.366205,1.86329,9.51748,0.194546,3.10311,...,G,9.76332,7.327710,-1.152370,6.34728,7.41776,0.775564,-0.155984,1,17.49220
1,165617,75100943,G,6.20385,-4.266610,0.456545,-4.47930,4.29097,-0.912070,3.03499,...,G,9.66898,7.273970,-2.821120,-5.71040,7.80188,-0.678625,-0.369977,1,11.55340
2,165617,75587682,G,19.28920,-4.212080,-0.651623,18.81210,4.26219,2.190460,-2.98811,...,G,9.82439,4.343940,-0.473505,8.79849,4.36967,1.449670,-0.108575,1,9.16361
3,165617,75660978,G,7.04268,-6.326780,-0.268545,3.08025,6.33248,0.469033,-3.09917,...,G,5.58571,4.474760,0.848935,-3.23185,4.55458,-0.660499,0.187488,1,12.47740
4,165617,75947690,G,7.27507,0.102966,-5.533080,-4.72122,5.53403,-0.773616,-1.55219,...,G,7.31811,-0.398831,6.940810,2.28247,6.95226,0.322677,1.628190,1,14.31590

In [7]:
f=pd.read_csv("C:\cern data/DoubleMuRun2011A.csv")

# pick columns that you would like to keep:


keep_col = ['px1','py1','pz1','px2', 'py2', 'pz2']
new_f = f[keep_col]

# saves the new csv with only momentum measurements to a new file:

new_f.to_csv("C:\cern data/newFile.csv", index=False)

In [5]:
# display the file:
new_f.head()

        px1       py1       pz1       px2       py2      pz2
0 -9.510430  0.366205   1.86329  7.327710 -1.152370  6.34728
1 -4.266610  0.456545  -4.47930  7.273970 -2.821120 -5.71040
2 -4.212080 -0.651623  18.81210  4.343940 -0.473505  8.79849
3 -6.326780 -0.268545   3.08025  4.474760  0.848935 -3.23185
4  0.102966 -5.533080  -4.72122 -0.398831  6.940810  2.28247

Below, Energy 1 and Energy 2 tables were selected from the file to make a comparison with calculated energy.

In [9]:
c = pd.read_csv('C:\cern data/DoubleMuRun2011A.csv')

keep = ['E1','E2']
c = c[keep]

c.to_csv('C:\cern data/energy_compare.csv', index = False)

In order to make the original file smaller, one might want to delete rows in the cvs file.